_target_: fish_vocoder.modules.generators.hifigan.HiFiGANGenerator
hop_length: ${model.hop_length}
upsample_rates: [8, 8, 2, 2, 2]  # aka. strides
upsample_kernel_sizes: [16, 16, 8, 2, 2]
resblock_kernel_sizes: [3, 7, 11]
resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
num_mels: ${model.num_mels}
upsample_initial_channel: 512
use_template: false
pre_conv_kernel_size: 7
post_conv_kernel_size: 7
