_target_: fish_vocoder.modules.generators.vocos.VocosGenerator
backbone:
  _target_: fish_vocoder.modules.encoders.convnext.ConvNeXtEncoder
  input_channels: ${model.num_mels}
  depths: [8]
  dims: [512]
  drop_path_rate: 0.1
  kernel_sizes: [7]
head:
  _target_: fish_vocoder.modules.generators.vocos.ISTFTHead
  dim: 512
  n_fft: ${model.n_fft}
  hop_length: ${model.hop_length}
  win_length: ${model.win_length}
  padding: same
